function createfigure(X1, Y1, Z1, X2, S1, C1)
%CREATEFIGURE(X1, Y1, Z1, X2, S1, C1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  X2:  scatter3 x
%  S1:  scatter3 s
%  C1:  scatter3 c

%  Auto-generated by MATLAB on 13-Apr-2020 16:52:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1);

% Create scatter3
scatter3(X2,X2,X2,S1,C1,'LineWidth',2);

% Create text
text('Parent',axes1,'String','  Origin','Position',[0 0 0]);

% Create zlabel
zlabel('Z (Millimeteres)');

% Create ylabel
ylabel('Y (Millimeteres)');

% Create xlabel
xlabel('X (Millimeteres)');

% Create title
title('Tongue Path w.r.t Fixed Reference Point');

view(axes1,[-188.832291673495 2.34800846936474]);
grid(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'Projection','perspective','XDir',...
    'reverse','YDir','reverse');
